language: ruby
install:
  - gem install awestruct therubyracer less redcarpet
script:
  - awestruct -P production
before_deploy:
  - npm i netlify-cli
deploy:
  provider: script
  skip_cleanup: true
  script:
    - node_modules/.bin/netlify -s blog-kaltepoth-de -t $ACCESS_TOKEN -p _site
  on:
    repo: chkal/blog.kaltepoth.de
    branch: master
env:
  global:
    secure: bI1Ciiwn7rzx4ByQ9JhcWK86lUa3KRFOrN8IQ6/3hUMmPgRzft7P2DF2botqJLdoDPkp+qSZDTLLuIoO2sqaWdq9oV0WsnBntKJwN7BaiCbynvKZhaWrqur7IPm9Imkmuz9NE4Ygd/MMKMX/Xh5vKN8bmDL1PD/Ry9xeTUE6vc8=
