language: ruby
install:
  - gem install awestruct therubyracer less
script:
  - awestruct -P production
deploy:
  provider: s3
  access_key_id: AKIAJSUGYSKIRPOS2QVA
  secret_access_key:
    secure: lHyNO1neEwtFhckc2Wme5a92ftYt8BWefOPpS9BePnbak99/h4tQxmRBjaepMwDxYobPHewormf5rf9T1dY7kFuipo23l7yoVH69kTTc6+GaB3JyQLlb00EtEaoxdbusDxFec0JHTk9K1e/V2KdbUzGMeANDBcFpqawy9NuEwk4=
  bucket: blog.kaltepoth.de
  skip_cleanup: true
  endpoint: blog.kaltepoth.de.s3-website-eu-west-1.amazonaws.com
  region: eu-west-1
  local-dir: _site
  acl: public_read
  on:
    repo: chkal/blog.kaltepoth.de
