profiles:
  development:
    base_url: http://localhost:4242
    disqus: chkal-blog-dev
    disqus_developer: true
  production:
    base_url: http://blog.kaltepoth.de
    google_analytics: UA-7295879-9
    disqus: chkal-blog
    disqus_generate_id: true
    deploy:
      host: kaltepoth.de
      path: /home/www/blog.kaltepoth.de/htdocs
